### ISSUE TITLE
Projection and lat/lon coordinates in floe grids do not fit to GPS track

### ISSUE THREAD

**Issue by nhutter** [awi-als-toolbox/awi-als-toolbox#15]
Niklas Neckel reported that the projected `x/y` coordinates as well as `lat/lon` coordinates does not match with the track of the GPS solutions.

- [x] Check the projection to which the ice drift corrections projects and if it is consistent through out the flight
- [x] Check if the projection of the ice drift correction fits to the projection specified in the config file `mosaic-als-f????????-griddef.ymal`
- [x] Implement consistent use of one projection for the final floe grid
- [x] Test new coordinates if the match fit flight track provided by Niklas Neckel.

**Comment by nhutter** [comment]
The projections used for the ice drift correction are different for each 30s segment as it is the stereographic projection centred around the median longitude and latitude of the reference station positions (Polarstern) resampled to the time of the 30s segment. Thus for each 30s segment the origin of the coordinates shifts slightly with the drift of Polarstern. I suspect this shift causes the slight spatial offsets between segments in the merged floe grids.

**Comment by nhutter** [comment]
As written above the ice drift correction does not use the projection specified in the config file.

**Comment by nhutter** [comment]
I updated [IceDrift](https://gitlab.awi.de/floenavi-crs/icedrift) package to allow for a user defined projection to use for the correction. The projection that I currently use for all segments is a stereographic projection that is centred around the median longitude and latitude of Polarstern's position during the entire flight period.

**Comment by shendric** [comment]
Hi @nhutter, I just added you to the list of icedrift maintainers, so that you can push your change to the source repo

**Comment by nhutter** [comment]
Solved in pull request #18
