### ISSUE TITLE
Merged grids filenaming convention

### ISSUE THREAD

**Issue by ajutila** [awi-als-toolbox/awi-als-toolbox#25]
Hi Nils,
If it is not too much of a trouble, could the filenames of the merged grids follow the same format as the individual 30-sec segments? The problem here is the grid resolution, which now is `0.5` instead of `0p50m` and having two `.`s in the filename can be sometimes a bit problematic (for example when using bash functions `dirname` and `basename`). I tried to look into the code where it is defined, but couldn't quickly find it.

**Comment by nhutter** [comment]
I fixed this and will push this in the next major update of the code.
