### ISSUE TITLE
Wrong definition of lon/lat grid

### ISSUE THREAD

**Issue by lzampier** [awi-als-toolbox/awi-als-toolbox#26]
Hi all, I was playing with the MOSAiC ALS dataset and I found an error in the grid description contained in the netCDF files. I encountered this problem both in the official data published on Zenodo and in the non-official files kindly shared by @nhutter.

The problem is illustrated in the picture below, where I am trying to plot a 6x6 subset of the lon/lat grid contained in the MOSAiC ALS dataset. The points are the first six rows and columns of the grid for each day. As you can see, the markers on the map are not forming a 6x6 mesh on the maps, but there is a certain degree of overlapping/chaos. This issue prevents using the data for interpolation purposes. Nils already indicated that this is an issue of the lon/lat grid, while the xc/yc grid does not exhibit this behavior.

I can try to circumvent the problem for my case by using the xc/yc grid and the projection information, but it would be great to solve the issue and make the data more usable. 

![Presentation1](https://user-images.githubusercontent.com/25898015/162256523-0e59151c-9f82-419d-a414-ffb0db4109b1.png)

**Comment by nhutter** [comment]
Thank you for opening an issue @lzampier. I managed to trace back the issue: The resolution of the ALS data is so high that it is not sufficient to output the latitude and longitude as single precision numpy float32 (which I find pretty impressive). In the plot below you can see that this basically bins the latitude values and leads to the distorted grids you observe. I changed the code to output double precision lat/lons for both floe grids and 30s-segments now, which should resolve this issue though increase the netcdf size.
![Figure 13](https://user-images.githubusercontent.com/25906056/162274545-3e99bd56-f346-457b-b777-0d5de0dfa912.png)

**Comment by lzampier** [comment]
Nice job @nhutter :) having such a high resolution is indeed impressive! Thank you for being so quick!
