### ISSUE TITLE
Add multiprocessing to batch gridding

### ISSUE THREAD

**Issue by shendric** [awi-als-toolbox/awi-als-toolbox#5]
At the moment the gridding process runs in a single process thal loops sequentially over all output segments. The process of gridding and writing netCDF files from the individual segments can easily be run in parallel. 

Requested Action: Evaluate and implement options (e.g. multiprocessing, dask, ...)

**Comment by nhutter** [comment]
I close this issue, since it is solved and the gridding process runs parallel and efficient with the pull requests #6 and #8
